### ISSUE TITLE
The metrics exposed should be dynamic (not static)

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap-plugin-collector-cpu#19]
For example, the metric catalog should contain
`/intel/procfs/cpu/*/active_jiffies` 
In addition to
`/intel/procfs/cpu/0/active_jiffies`

Since the number of CPU cores is fixed it could be reasonable to argue that this plugin should populate the catalog with both the dynamic (schema) and static namespaces that can be collected against.

See also https://github.com/intelsdi-x/snap/issues/980

**Comment by elemoine** [comment]
I would treat CPUs as dynamic resources, just like disks. The two reasons that I see: CPU hotplug, and not making the CPU plugin a special case.

**Comment by obourdon** [comment]
Just for a better understanding: what is the rationale of exposing both the static and dynamic metrics as opposed to only expose dynamic part (like for snap-collector-mock2) ?

**Comment by elemoine** [comment]
> Does it have to do with the fact that with dynamic metrics you might not be able to specify a fixed metric in a task ?

And even if the metric is dynamic (e.g. /intel/procfs/cpu.*/user_percentage) I don't see why it would prevent the use of fixed metrics (e.g /intel/procfs/cpu/0/user_percentage) in the task workflow definition. I am just stating this from the user point of view.

**Comment by elemoine** [comment]
> I tried to get only /intel/mock/host4/baz in the example mock-file.json using mock collector and got error saying 'Metric not found'

Thanks for testing. This is related to my [previous comment](https://github.com/intelsdi-x/snap-plugin-collector-cpu/issues/19#issuecomment-226099306). Again, from the user point of view, I wonder if this should fail. It would be great the have the Snap developers' opinions about this.

**Comment by candysmurf** [comment]
Agreed with @elemoine, we should support both the dynamic and the static metrics so that we may get as many metrics as we like or as little as one metric that we care.

Also, note that it's up to the plugin authors to support dynamic metric queries by utilizing what Snap framework provides.

**Comment by IzabellaRaulin** [comment]
@elemoine, such case that you mentioned - trying to get only `/intel/mock/host4/baz`  when the cataloged metric is `/intel/mock/*/baz` seems to be covered by https://github.com/intelsdi-x/snap/pull/907 (work in progress)

But notice, that there is no information which e.g. hosts are available - if user puts in task manifest `/intel/mock/host10/baz` as requested metric to collect, but there is no host10, error `Metric not found` occures.

Referring to cpu plugin, the reason why at first decided to expose all of cpu metrics explicitly and not to treat them as dynamic metrics might have been that these metrics are rather fixed in comparison with others examples of using dynamic metrics as we have in snap-plugin-collector-docker (ids of available docker containers) or snap-plugin-collector-processes (names of existing processes).

**So, my question is what is the decision in this case?** (by the way, it should be also recorded in plugin's BKM docs)

If there is a plan that  metrics catalog will contain two forms (static and dynamic) of the same metric, **please, consider such case**: 

a) When metric catalog contains:
`/intel/procfs/cpu/*/active_jiffies`
`/intel/procfs/cpu/0/active_jiffies `
`/intel/procfs/cpu/1/active_jiffies `
`/intel/procfs/cpu/all/active_jiffies `

b) and in task manifest there is request to collect such metric:
`/intel/procfs/cpu/*/active_jiffies` 

c) what means that the following metrics will be collected:
(all metrics which match with `/intel/procfs/cpu/*/active_jiffies` where `*` means everything),

`/intel/procfs/cpu/*/active_jiffies`
`/intel/procfs/cpu/0/active_jiffies `
`/intel/procfs/cpu/1/active_jiffies `
`/intel/procfs/cpu/all/active_jiffies `

d) so, a plugin will return such metrics:
 (notice, that the first three of them came from `/intel/procfs/cpu/*/active_jiffies` as itself): 
`/intel/procfs/cpu/0/active_jiffies `
`/intel/procfs/cpu/1/active_jiffies `
`/intel/procfs/cpu/all/active_jiffies `
`/intel/procfs/cpu/0/active_jiffies `
`/intel/procfs/cpu/1/active_jiffies `
`/intel/procfs/cpu/all/active_jiffies `


As we can see, if the both form (static and dynamic) of a metric are cataloged, there is a possibility that a plugin will return the same metric two times. What's about that?

**Comment by candysmurf** [comment]
@IzabellaRaulin, by using your example,

Metric _`Catalog`_ A:
      /intel/procfs/cpu/*/active_jiffies

_`Metrics`_ returned by metric catalog A:
     /intel/procfs/cpu/0/active_jiffies
    /intel/procfs/cpu/1/active_jiffies
    /intel/procfs/cpu/all/active_jiffies

The above is fine. There may be metrics like:
    /intel/procfs/name
   /intel/procfs/description

Those metrics aren't bonded to a particular CPU.  Snap should still allow users to collect those.

Hope this helps.

**Comment by obourdon** [comment]
@IzabellaRaulin this is exactly what I have experimented when I started working on the same are for disk collector (see [my local copy](https://github.com/intelsdi-x/snap-plugin-collector-disk/compare/master...obourdon:all_in_1). At last because of the problem of duplicates you mention above, I decided to remove the addition of static metrics at [line 153](https://github.com/intelsdi-x/snap-plugin-collector-disk/compare/master...obourdon:all_in_1#diff-0e94f1a71d469b8ab3d3c4ff04bf38b4R153) to only keep dynamic metric.

**Comment by obourdon** [comment]
Fixed by PR #32

**Comment by obourdon** [comment]
@intelsdi-x/snap-maintainers could you please review the PR #32 and merge if appropriate ?

**Comment by jcooklin** [comment]
> I decided to remove the addition of static metrics at line 153 to only keep dynamic metric.

I agree.  

I added https://github.com/intelsdi-x/snap/issues/1144 which describes adding the current values for dynamic elements when getting metrics.

**Comment by katarzyna-z** [comment]
This issue was addressed by #32.
